name: "Meio.Mask"

web: "[mootools.net/forge/p/meiomask](http://mootools.net/forge/p/meiomask)"

description: "MeioMask - A mootools plugin for masking text inputs"

authors: "[Fábio M. Costa](http://meiocodigo.com/)"

license: "MIT License"

copyright: "&copy; 2010, Fábio M. Costa"

sources:
  - "Source/Meio.Mask.js"
  - "Source/Meio.Mask.Fixed.js"
  - "Source/Meio.Mask.Regexp.js"
  - "Source/Meio.Mask.Reverse.js"
  - "Source/Meio.Mask.Repeat.js"
  - "Source/Meio.Mask.Extras.js"

# Values for MooTools forge

author: fabiomiranda

current: 2.0.3

docs: http://meiocodigo.com/projects/moomeiomask

demo: http://jsfiddle.net/fabiomcosta/8TFvp/252/

category: Forms

tags: [input, mask]

